//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.functions")]
    public interface functions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetActions", ReplyAction="http://tempuri.org/functions/GetActionsResponse")]
        lib_wfc.Action[] GetActions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetActions", ReplyAction="http://tempuri.org/functions/GetActionsResponse")]
        System.Threading.Tasks.Task<lib_wfc.Action[]> GetActionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetServices", ReplyAction="http://tempuri.org/functions/GetServicesResponse")]
        lib_wfc.Service[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetServices", ReplyAction="http://tempuri.org/functions/GetServicesResponse")]
        System.Threading.Tasks.Task<lib_wfc.Service[]> GetServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetPerson", ReplyAction="http://tempuri.org/functions/GetPersonResponse")]
        lib_wfc.Person GetPerson(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetPerson", ReplyAction="http://tempuri.org/functions/GetPersonResponse")]
        System.Threading.Tasks.Task<lib_wfc.Person> GetPersonAsync(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetOrder", ReplyAction="http://tempuri.org/functions/GetOrderResponse")]
        lib_wfc.Order GetOrder(int id_order, int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetOrder", ReplyAction="http://tempuri.org/functions/GetOrderResponse")]
        System.Threading.Tasks.Task<lib_wfc.Order> GetOrderAsync(int id_order, int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/AddOrder", ReplyAction="http://tempuri.org/functions/AddOrderResponse")]
        bool AddOrder(lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/AddOrder", ReplyAction="http://tempuri.org/functions/AddOrderResponse")]
        System.Threading.Tasks.Task<bool> AddOrderAsync(lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetAllOrders", ReplyAction="http://tempuri.org/functions/GetAllOrdersResponse")]
        lib_wfc.Order[] GetAllOrders(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/GetAllOrders", ReplyAction="http://tempuri.org/functions/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<lib_wfc.Order[]> GetAllOrdersAsync(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/Registration", ReplyAction="http://tempuri.org/functions/RegistrationResponse")]
        void Registration(string name, int phone, string email, System.DateTime birth, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/Registration", ReplyAction="http://tempuri.org/functions/RegistrationResponse")]
        System.Threading.Tasks.Task RegistrationAsync(string name, int phone, string email, System.DateTime birth, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/Autorization", ReplyAction="http://tempuri.org/functions/AutorizationResponse")]
        lib_wfc.Person Autorization(string login, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/Autorization", ReplyAction="http://tempuri.org/functions/AutorizationResponse")]
        System.Threading.Tasks.Task<lib_wfc.Person> AutorizationAsync(string login, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/OrderPrice", ReplyAction="http://tempuri.org/functions/OrderPriceResponse")]
        int OrderPrice(lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/OrderPrice", ReplyAction="http://tempuri.org/functions/OrderPriceResponse")]
        System.Threading.Tasks.Task<int> OrderPriceAsync(lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/SaveOrder", ReplyAction="http://tempuri.org/functions/SaveOrderResponse")]
        void SaveOrder(int id_order, int id_client, lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/SaveOrder", ReplyAction="http://tempuri.org/functions/SaveOrderResponse")]
        System.Threading.Tasks.Task SaveOrderAsync(int id_order, int id_client, lib_wfc.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/SavePerson", ReplyAction="http://tempuri.org/functions/SavePersonResponse")]
        void SavePerson(int id_client, lib_wfc.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/functions/SavePerson", ReplyAction="http://tempuri.org/functions/SavePersonResponse")]
        System.Threading.Tasks.Task SavePersonAsync(int id_client, lib_wfc.Person person);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface functionsChannel : client.ServiceReference1.functions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class functionsClient : System.ServiceModel.ClientBase<client.ServiceReference1.functions>, client.ServiceReference1.functions {
        
        public functionsClient() {
        }
        
        public functionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public functionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public functionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public functionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public lib_wfc.Action[] GetActions() {
            return base.Channel.GetActions();
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Action[]> GetActionsAsync() {
            return base.Channel.GetActionsAsync();
        }
        
        public lib_wfc.Service[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Service[]> GetServicesAsync() {
            return base.Channel.GetServicesAsync();
        }
        
        public lib_wfc.Person GetPerson(int id_client) {
            return base.Channel.GetPerson(id_client);
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Person> GetPersonAsync(int id_client) {
            return base.Channel.GetPersonAsync(id_client);
        }
        
        public lib_wfc.Order GetOrder(int id_order, int id_client) {
            return base.Channel.GetOrder(id_order, id_client);
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Order> GetOrderAsync(int id_order, int id_client) {
            return base.Channel.GetOrderAsync(id_order, id_client);
        }
        
        public bool AddOrder(lib_wfc.Order order) {
            return base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderAsync(lib_wfc.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public lib_wfc.Order[] GetAllOrders(int id_client) {
            return base.Channel.GetAllOrders(id_client);
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Order[]> GetAllOrdersAsync(int id_client) {
            return base.Channel.GetAllOrdersAsync(id_client);
        }
        
        public void Registration(string name, int phone, string email, System.DateTime birth, string pas) {
            base.Channel.Registration(name, phone, email, birth, pas);
        }
        
        public System.Threading.Tasks.Task RegistrationAsync(string name, int phone, string email, System.DateTime birth, string pas) {
            return base.Channel.RegistrationAsync(name, phone, email, birth, pas);
        }
        
        public lib_wfc.Person Autorization(string login, string pas) {
            return base.Channel.Autorization(login, pas);
        }
        
        public System.Threading.Tasks.Task<lib_wfc.Person> AutorizationAsync(string login, string pas) {
            return base.Channel.AutorizationAsync(login, pas);
        }
        
        public int OrderPrice(lib_wfc.Order order) {
            return base.Channel.OrderPrice(order);
        }
        
        public System.Threading.Tasks.Task<int> OrderPriceAsync(lib_wfc.Order order) {
            return base.Channel.OrderPriceAsync(order);
        }
        
        public void SaveOrder(int id_order, int id_client, lib_wfc.Order order) {
            base.Channel.SaveOrder(id_order, id_client, order);
        }
        
        public System.Threading.Tasks.Task SaveOrderAsync(int id_order, int id_client, lib_wfc.Order order) {
            return base.Channel.SaveOrderAsync(id_order, id_client, order);
        }
        
        public void SavePerson(int id_client, lib_wfc.Person person) {
            base.Channel.SavePerson(id_client, person);
        }
        
        public System.Threading.Tasks.Task SavePersonAsync(int id_client, lib_wfc.Person person) {
            return base.Channel.SavePersonAsync(id_client, person);
        }
    }
}
